version: 1.0.0.{build}
clone_folder: c:\gopath\src\github.com\clpo13\bls-go
environment:
  GOPATH: c:\gopath
  matrix:
    - GOROOT: c:\go110
    - GOROOT: c:\go19
install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;%GOROOT%\bin;%PATH%
  - go version
  - go env
build_script:
  - go build
test_script:
  - go test -v